apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  creationTimestamp: null
  name: dev-cluster
spec:
  clusterNetwork:
    cni: cilium
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
  datacenterRef:
    kind: DockerDatacenterConfig
    name: dev-cluster
  externalEtcdConfiguration:
    count: 1
  gitOpsRef:
    kind: GitOpsConfig
    name: dev-cluster
  kubernetesVersion: "1.21"
  workerNodeGroupConfigurations:
  - count: 1
status: {}

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: DockerDatacenterConfig
metadata:
  creationTimestamp: null
  name: dev-cluster
spec: {}
status: {}

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: GitOpsConfig
metadata:
  creationTimestamp: null
  name: dev-cluster
spec:
  flux:
    github:
      branch: main
      clusterConfigPath: clusters/dev-cluster
      fluxSystemNamespace: flux-system
      owner: snogamis
      personal: true
      repository: eks-anywhere-gitops
status: {}

---
